name: 🤖 Auto approve when success

on:
  workflow_run:
    workflows: ['⚙️ Build demo', '⚙️ Build lib', '⚙️ Lint', '⚙️ Tests']
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref != 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - uses: taiga-family/ci/actions/setup/checkout@v1.23.0
      - uses: taiga-family/ci/actions/setup/variables@v1.23.0
      - uses: taiga-family/ci/actions/auto/approve/double@v1.23.0
        if: env.TAIGA_FAMILY_BOT_IS_AUTHOR == 'true'
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.ref != 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - uses: actions/github-script@v5
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⛔ Some jobs have fallen, we can’t set auto approve!'
            })
