name: 🤖 Auto cleanup caches by a branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/./.github/actions/cleanup-cache@1.2.0
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
          token: ${{ secrets.GITHUB_TOKEN }}
