name: 🤖 Auto approve
on: pull_request

jobs:
  automated-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiga-family/ci/./.github/actions/approve@main
        with:
          token1: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
