name: 🤖 Auto cleanup caches by a branch
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/cleanup-cache@1.7.5
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
