name: 🤖 Auto sync submodule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 */2 * *' # At 11:00 PM, every 2 days

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.25.8
      - uses: taiga-family/ci/actions/setup/config/git@v1.25.8
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/git/sync-submodule@v1.25.8
      - uses: taiga-family/ci/actions/git/status@v1.25.8
        id: git
      - uses: taiga-family/ci/actions/run/npm/install@v1.25.8
        if: steps.git.outputs.modified == 'true'
      - name: Create Pull Request
        if: steps.git.outputs.modified == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          branch: deps/submodule/${{ github.head_ref || github.ref_name }}
          commit-message: 'chore(deps): update taiga-ui submodule'
          title: 'chore(deps): update taiga-ui submodule'
