name: 🤖 Auto approve
on: pull_request

jobs:
  automated-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3.2.1
        with:
          review-message: 'LGTM (Automated approved)'
          github-token: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: hmarr/auto-approve-action@v3.2.1
        with:
          review-message: 'LGTM (Automated approved)'
