name: ⚙️ Build lib
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.0
      - uses: taiga-family/ci/actions/setup/node@v1.87.0
      - run: npx nx build editor

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
