name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches: [main, 'v[0-9]+.x']

jobs:
  build-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.58.1
      - uses: taiga-family/ci/actions/setup/variables@v1.58.1
      - uses: taiga-family/ci/actions/setup/node@v1.58.1
        with:
          validate-peer-deps: false

      - run: npm run build

concurrency:
  group: build-demo-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
