name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.9.2
      - uses: taiga-family/ci/actions/setup-node@1.9.2

      - name: Build demo
        run: npm run build

concurrency:
  group: build-demo-${{ github.head_ref }}
  cancel-in-progress: true
