name: ⚙️ Build lib
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build libs
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: recursive
      - uses: taiga-family/ci/actions/setup/variables@1.20.0
      - uses: taiga-family/ci/actions/setup/node@1.20.0
      - run: npx nx build tui-editor

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
