name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@v1.93.3
      - uses: taiga-family/ci/actions/setup/node@v1.93.3
      - run: npx nx prerender editor-demo

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
