name: Build lib
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build library
        run: npx nx build tui-editor

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
