name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: recursive
      - uses: taiga-family/ci/actions/variables@1.13.1
      - uses: taiga-family/ci/actions/setup-node@1.13.1
      - run: npm run build

concurrency:
  group: build-demo-${{ github.head_ref }}
  cancel-in-progress: true
