name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.60.0
      - uses: taiga-family/ci/actions/setup/variables@v1.60.0
      - uses: taiga-family/ci/actions/setup/node@v1.60.0
      - run: npx nx prerender editor-demo

concurrency:
  group: build-demo-${{ github.head_ref }}
  cancel-in-progress: true
