name: ⚙️ Build lib
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build libs
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/variables@1.12.2
      - uses: taiga-family/ci/actions/setup-node@1.12.2

      - name: Build library
        run: npx nx build tui-editor

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
