name: ⚙️ Build demo
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/variables@1.12.0
      - uses: taiga-family/ci/actions/setup-node@1.12.0

      - name: Build demo
        run: npm run build

concurrency:
  group: build-demo-${{ github.head_ref }}
  cancel-in-progress: true
