name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.44.5
      - uses: taiga-family/ci/actions/setup/variables@v1.44.5
      - uses: taiga-family/ci/actions/setup/node@v1.44.5
      - run: npx nx build editor-demo
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          projectId: tinkoff-tui-editor
          expires: 1d

concurrency:
  group: firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
