name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@v1.93.5
      - uses: taiga-family/ci/actions/setup/node@v1.93.5
      - run: npx nx prerender editor-demo -c github
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.93.5
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
