name: 🚀 Deploy
on: pull_request

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@v1.93.5
      - uses: taiga-family/ci/actions/setup/node@v1.93.5
      - run: npx nx build editor-demo
      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: taiga-editor
          target: taiga-editor
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
