name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.85.0
      - uses: taiga-family/ci/actions/setup/node@v1.85.0

      - run: npx nx prerender editor-demo -c github

      - uses: taiga-family/ci/actions/deploy/github-pages@v1.85.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
