name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: recursive
      - uses: taiga-family/ci/actions/setup/variables@1.20.0
      - uses: taiga-family/ci/actions/setup/node@1.20.0
      - run: npx nx build-gh-pages editor-demo
      - uses: taiga-family/ci/actions/deploy/github-pages@1.20.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
