name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: taiga-family/ci/actions/variables@1.11.1
      - uses: taiga-family/ci/actions/setup-node@1.11.1

      - name: Build demo for Github Pages
        run: npx nx build-gh-pages demo

      - uses: taiga-family/ci/actions/setup-deploy@1.11.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
