name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.7.0
      - uses: taiga-family/ci/actions/setup-node@1.7.0

      - name: Build demo for Github Pages
        run: npx nx build-gh-pages demo

      - uses: taiga-family/ci/actions/setup-deploy@1.7.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
