name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.3.0
      - uses: taiga-family/ci/actions/setup-node@1.3.0

      - run: npx nx build demo

      - name: Debug output
        run: tree dist/demo -P '*.html'

      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          projectId: tinkoff-tui-editor
          expires: 1d

concurrency:
  group: firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
