name: 🚀 Deploy / preview

on: pull_request

  IS_FORK: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
  IS_DEPENDABOT: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - run: npx nx build demo

      - name: Debug output
        run: tree dist/demo -P '*.html'

      - name: Deploy preview

        uses: FirebaseExtended/action-hosting-deploy@v0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          projectId: tinkoff-tui-editor
          expires: 1d

concurrency:
  group: firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
