name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.58.1
      - uses: taiga-family/ci/actions/setup/variables@v1.58.1
      - uses: taiga-family/ci/actions/setup/node@v1.58.1
        with:
          validate-peer-deps: false

      - run: npx nx prerender editor-demo
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '<base href="/">'
          replace: '<base href="/editor/">'
          include: 'dist/demo/browser/index.html'
          regex: false

      - uses: taiga-family/ci/actions/deploy/github-pages@v1.58.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/demo/browser

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
