name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/./.github/actions/variables@1.2.1
      - uses: taiga-family/ci/./.github/actions/setup-node@1.2.1

      - name: Build demo for Github Pages
        run: npx nx build-gh-pages demo

      - uses: taiga-family/ci/./.github/actions/setup-deploy@1.2.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
