name: 🚀 Deploy / preview
on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@v1.93.3
      - uses: taiga-family/ci/actions/setup/node@v1.93.3
      - run: npx nx build editor-demo
      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          projectId: taiga-editor
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
