name: ⚙️ E2E tests
on:
  pull_request:

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: taiga-family/ci/actions/setup/variables@v1.93.2
      - uses: taiga-family/ci/actions/setup/node@v1.93.2
      - uses: taiga-family/ci/actions/setup/playwright@v1.93.2
      - run: npx nx prerender editor-demo
      - uses: taiga-family/ci/actions/run/serve@v1.93.2
        with:
          port: ${{ env.NG_SERVER_PORT }}
          directory: ${{ env.DIST }}
          replaceBaseUrlFrom: /editor/
          replaceBaseUrlTo: /

      - run: npx nx e2e editor-demo-playwright -- --update-snapshots

      - uses: taiga-family/ci/actions/run/clone@v1.93.2
        with:
          branch: snapshots/demo/next/${{ github.base_ref }}
          destination: ${{ env.DIST_NEXT }}

      - uses: taiga-family/ci/actions/run/serve@v1.93.2
        with:
          port: ${{ env.NG_SERVER_PORT }}
          directory: ${{ env.DIST_NEXT }}
          replaceBaseUrlFrom: /editor/
          replaceBaseUrlTo: /

      - run: npx nx e2e editor-demo-playwright
        continue-on-error: true

      - uses: actions/upload-artifact@v4.4.1
        with:
          path: ./projects/demo-playwright/tests-results/**/*-diff.png
          name: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
          if-no-files-found: ignore
          compression-level: 0
          retention-days: 1

      - id: diff-checker
        run: |
          echo "diff_exist=$(find ./projects/demo-playwright/tests-results -regex '.*diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
      - if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ./projects/demo-playwright/tests-results -regex '.*diff\.png$' -exec echo "{}" \;
          exit 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
