name: ⚙️ E2E
on:
  pull_request:

jobs:
  result:
    if: ${{ !contains(github.head_ref , 'release/') }}
    name: E2E result
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
