name: ⚙️ E2E
on:
  pull_request:

jobs:
  build-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.3.0
      - uses: taiga-family/ci/actions/rebase@1.3.0
        continue-on-error: true
      - uses: taiga-family/ci/actions/setup-node@1.3.0

      - name: Building demo-app of git-branch without cache
        run: npx nx build demo --output-path ${{ env.DIST }}

      - name: Upload cache / ${{ env.CACHE_DIST_KEY }}
        uses: actions/cache/save@v3.3.1
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

  cypress:
    needs: [build-demo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.3.0
      - uses: taiga-family/ci/actions/setup-node@1.3.0

      - name: Download cache / ${{ env.CACHE_DIST_KEY }}
        uses: actions/cache/restore@v3.3.1
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Serve ${{ env.DIST }} in background
        run: npx nx serve-compiled demo --path ${{ env.DIST }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST }}
        run: npx nx e2e demo-integrations

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Download ${{ env.DIST_NEXT }} for serve locally
        run: |
          git clone \
                --depth 1 \
                --branch snapshots/demo/next/${{ github.base_ref }} \
                https://github.com/taiga-family/tui-editor.git ${{ env.DIST_NEXT }}

      - name: Serve ${{ env.DIST_NEXT }} in background
        run: npx nx serve-compiled demo --path ${{ env.DIST_NEXT }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST_NEXT }}
        continue-on-error: true
        run: npx nx e2e demo-integrations

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Upload artifacts / ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ${{ env.SNAPSHOTS_PATH }}/**/*.diff.png
          name: ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
          if-no-files-found: ignore
          retention-days: 1

  result:
    if: ${{ !contains(github.head_ref , 'release/') }}
    name: E2E result
    needs: [cypress]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.3.0

      - name: Download artifacts / ${{ env.SNAPSHOTS_KEY }}
        continue-on-error: true
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ env.SNAPSHOTS_KEY }}
          path: ${{ env.SNAPSHOTS_PATH }}

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "diff_exist=$(find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' -exec echo "{}" \;
          exit 1

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
