name: ⚙️ E2E tests
on:
  pull_request:

jobs:
  build-demo:
    name: Build demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase
        continue-on-error: true

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Building demo-app of git-branch without cache
        run: npx nx build demo --output-path ${{ env.DIST }}

      - name: Upload cache / ${{ env.CACHE_DIST_KEY }}
        uses: actions/cache/save@v3.3.1
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

  cypress:
    needs: [build-demo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Download cache / ${{ env.CACHE_DIST_KEY }}
        uses: actions/cache/restore@v3.3.1
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Serve ${{ env.DIST }} in background
        run: npx nx serve-compiled demo --path ${{ env.DIST }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST }}
        run: npx nx e2e demo-integrations

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Download ${{ env.DIST_NEXT }} for serve locally
        run: |
          git clone \
                --depth 1 \
                --branch snapshots/demo/next/${{ github.base_ref }} \
                https://github.com/taiga-family/tui-editor.git ${{ env.DIST_NEXT }}

      - name: Serve ${{ env.DIST_NEXT }} in background
        run: npx nx serve-compiled demo --path ${{ env.DIST_NEXT }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST_NEXT }}
        continue-on-error: true
        run: npx nx e2e demo-integrations

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Upload artifacts / ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ${{ env.SNAPSHOTS_PATH }}/**/*.diff.png
          name: ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
          if-no-files-found: ignore
          retention-days: 1

  result:
    name: result
    needs: [cypress]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables

      - name: Download artifacts / ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
        continue-on-error: true
        uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ env.SNAPSHOTS_ARTIFACTS_KEY }}
          path: ${{ env.SNAPSHOTS_PATH }}

      - name: Upload cache / ${{ env.SNAPSHOTS_CACHE_KEY }}
        uses: actions/cache/save@v3.3.1
        with:
          path: ${{ env.SNAPSHOTS_PATH }}
          key: ${{ env.SNAPSHOTS_CACHE_KEY }}

      - name: Debug output
        continue-on-error: true
        run: tree ${{ env.SNAPSHOTS_PATH }}

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
