name: ⚙️ E2E tests
on:
  pull_request:

jobs:
  e2e:
    if: ${{ !contains(github.head_ref , 'release/') }}
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.51.5
      - uses: taiga-family/ci/actions/setup/variables@v1.51.5
      - uses: taiga-family/ci/actions/setup/node@v1.51.5

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Building demo-app of git-branch without cache
        run: npx nx build editor-demo --output-path ${{ env.DIST }}

      - name: Serve ${{ env.DIST }} in background
        run: npx nx serve-compiled editor-demo --path ${{ env.DIST }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST }}
        run: npx nx e2e demo-playwright -- --update-snapshots

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Download ${{ env.DIST_NEXT }} for serve locally
        run: |
          git clone \
                --depth 1 \
                --branch snapshots/demo/next/${{ github.base_ref }} \
                https://github.com/taiga-family/tui-editor.git ${{ env.DIST_NEXT }}

      - name: Serve ${{ env.DIST_NEXT }} in background
        run: npx nx serve-compiled demo --path ${{ env.DIST_NEXT }} --port ${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.DIST_NEXT }}
        continue-on-error: true
        run: npx nx e2e editor-demo-playwright

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Debug output
        continue-on-error: true
        run: tree ./projects/demo-playwright/tests-results

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "diff_exist=$(find ./total -regex '.*diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ./total -regex '.*diff\.png$' -exec echo "{}" \;
          exit 1

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
