name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/variables@1.12.4
      - uses: taiga-family/ci/actions/setup-node@1.12.4

      - name: Lint check
        run: |
          npm run typecheck
          npm run prettier -- --check
          npm run stylelint
          npm run lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
