name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.3.0
      - uses: taiga-family/ci/actions/setup-node@1.3.0

      - name: Lint check
        run: |
          npm run typecheck
          npm run format -- --check
          npm run stylelint
          npm run lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
