name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: recursive
      - uses: taiga-family/ci/actions/setup/variables@1.20.0
      - uses: taiga-family/ci/actions/setup/node@1.20.0
      - run: npm run typecheck
      - run: npm run prettier -- --check
      - run: npm run stylelint
      - run: npm run lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
