name: ⚙️ Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.46.0
      - uses: taiga-family/ci/actions/setup/variables@v1.46.0
      - uses: taiga-family/ci/actions/setup/node@v1.46.0
      - run: npm run typecheck
      - run: npm run prettier -- --check
      - run: npm run stylelint
      - run: npm run lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true
