name: ⚠️ Release
on:
  workflow_dispatch:
    inputs:
      forcePush:
        type: boolean
        required: false
        description: --force-publish package
      mode:
        type: choice
        description: force package to be versioned (depend --force-publish)
        required: false
        default: minor
        options:
          - patch
          - minor
          - major
          - prerelease

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    env:
      GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.3
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/variables@v1.66.3
      - uses: taiga-family/ci/actions/setup/node@v1.66.3
      - uses: taiga-family/ci/actions/setup/config/git@v1.66.3
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/config/npm@v1.66.3
        with:
          token: ${{ secrets.TAIGA_UI_SCOPE_NPM_TOKEN }}

      - run: git pull --rebase --recurse-submodules

      - run: |
          if [[ "${{ github.event.inputs.forcePush }}" == "true" ]]; then
            if [[ "${{ github.event.inputs.mode }}" != "prerelease" ]]; then
                npx release-it "${{ github.event.inputs.mode }}" --increment --ci --github.release
            else
                npx release-it --preRelease=alpha --ci
            fi
          else
              npx release-it --increment --ci --github.release
          fi
