name: ⚠️ Release @tbank/tui-editor
on:
  workflow_dispatch:
    inputs:
      forcePush:
        type: boolean
        required: false
        description: --force-publish package
      mode:
        type: choice
        description: force package to be versioned (depend --force-publish)
        required: false
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  run-release:
    name: Run release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.58.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/node@v1.58.1
        with:
          validate-peer-deps: false

      - uses: taiga-family/ci/actions/setup/config/git@v1.58.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      - uses: taiga-family/ci/actions/setup/config/npm@v1.58.1
        with:
          token: ${{ secrets.TBANK_SCOPE_NPM_TOKEN }}

      - name: Lerna update version of packages
        if: always()
        run: |
          if [[ ${{ github.event.inputs.forcePush }} == "true" ]]; then
            npx lerna version ${{ github.event.inputs.mode }} --no-private --force-publish
          else
              npx lerna version --no-private
          fi

      - run: npx nx build tui-editor

      - run: npx nx publish tui-editor
        if: always()

      - id: info
        run: |
          echo "version=v$(node -p "require('./projects/tui-editor/package.json').version")" >> $GITHUB_OUTPUT

      - name: Announce to Telegram
        uses: taiga-family/ci/actions/messenger/telegram/announce@v1.58.1
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: ${{ steps.info.outputs.version }}
          textLink: '@tbank/tui-editor'

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
