name: 🚀 Snapshots
on:
  push:
    branches: [main]

jobs:
  snapshots-next:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.39.1
      - uses: taiga-family/ci/actions/setup/variables@v1.39.1
      - uses: taiga-family/ci/actions/setup/node@v1.39.1
      - run: npx nx build editor-demo
      - uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: snapshots-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
