name: 🚀 Snapshots
on:
  push:
    branches: [main, 'v[0-9]+.x']

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.66.3
      - uses: taiga-family/ci/actions/setup/variables@v1.66.3
      - uses: taiga-family/ci/actions/setup/node@v1.66.3

      - run: npx nx build editor-demo
      - run: tree ${{ env.DIST }} -P '*.html'

      - id: info
        run: |
          echo "version=$(node -p "require('./projects/editor/package.json').version.split('.')?.[0]")" >> $GITHUB_OUTPUT

      - name: Publish next snapshots
        if: ${{ contains(github.head_ref || github.ref_name, 'main') }}
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - name: Publish v${{ steps.info.outputs.version }}.x snapshots
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/v${{ steps.info.outputs.version }}.x
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: snapshots-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
