name: 🚀 Snapshots
on:
  push:
    branches: [main]

jobs:
  snapshots-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
        with:
          submodules: recursive
      - uses: taiga-family/ci/actions/variables@1.13.0
      - uses: taiga-family/ci/actions/setup-node@1.13.0
      - run: npx nx build editor-demo
      - name: Publish snapshots
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          FOLDER: ${{ env.DIST }}
          BRANCH: snapshots/demo/next/${{ github.head_ref || github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: snapshots-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
