name: ⚙️ Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/./.github/actions/variables@1.2.0
      - uses: taiga-family/ci/./.github/actions/setup-node@1.2.0

      - name: Run tests
        run: npx nx test tui-editor

      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/tui-editor
          flags: tui-editor
          name: tui-editor

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
