name: Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run tests
        run: npx nx test tui-editor

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/tui-editor
          flags: tui-editor
          name: tui-editor

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
