name: ⚙️ Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: taiga-family/ci/actions/setup/variables@v1.93.2
      - uses: taiga-family/ci/actions/setup/node@v1.93.2
      - run: npx nx test editor --nxBail
      - uses: codecov/codecov-action@v4.6.0
        with:
          directory: ./coverage/editor
          flags: editor
          name: editor

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
